[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
maxUploadSize = 50

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[theme]
base = "dark"
primaryColor = "#9ef08a"
backgroundColor = "#16181f"
secondaryBackgroundColor = "#1f222a"
textColor = "#f0f1f5"
font = "sans serif"
