[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
maxUploadSize = 50

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[theme]
base = "light"
